#ifndef RAND_DATA_TYPE_H_
#define RAND_DATA_TYPE_H_

#pragma once

//随机分布类型
enum RAND_DIS_TYPE
{
	RAND_DIS_TYPE_SMALLINT = 0,	//一个整数集上的离散均匀分布
	RAND_DIS_TYPE_INT,			//一个整数集上的离散均匀分布
	RAND_DIS_TYPE_01,			//[0, 1)上的连续均匀分布
	RAND_DIS_TYPE_REAL,			//[min, max)上的连续均匀分布
	RAND_DIS_TYPE_BERNOULLI,	//伯努利分布
	RAND_DIS_TYPE_GEOMETRIC,	//几何分布
	RAND_DIS_TYPE_TRIANGLE,		//三角分布
	RAND_DIS_TYPE_EXPONENTIAL,	//指数分布
	RAND_DIS_TYPE_NORMAL,		//正态分布
	RAND_DIS_TYPE_LOGNORMAL,	//对数分布
	RAND_DIS_TYPE_ON_SPHERE,	//球面上的均匀分布
	RAND_DIS_TYPE_BETA,			//贝塔分布
	RAND_DIS_TYPE_BINOMIAL,		//二项分布
	RAND_DIS_TYPE_CAUCHY,		//柯西分布
	RAND_DIS_TYPE_DISCRETE,		//离散分布
};

//随机数源产生算法 算法速度有高到低，算法质量由低到高
enum  RAND_GEN_ALGORITHM_TYPE
{
	RAND_GEN_ALGORITHM_TYPE_RAND48=0,				//rand48算法随机数发生器
	RAND_GEN_ALGORITHM_TYPE_MT19937,				//mt19937算法随机数发生器
	RAND_GEN_ALGORITHM_TYPE_MT19937_64,				//mt19937-64算法随机数发生器
	RAND_GEN_ALGORITHM_TYPE_LAGGED_FIBONACCI19937,	//lagged_fibonacci19937算法随机数发生器
};

#undef RAND_DIS_NUM_SCOPE_MIN
#undef RAND_DIS_NUM_SCOPE_I64MAX
#undef RAND_DIS_NUM_SCOPE_I32MAX
#define RAND_DIS_NUM_SCOPE_MIN I64(0)
#define RAND_DIS_NUM_SCOPE_I64MAX I64(1152921504606846976)
#define RAND_DIS_NUM_SCOPE_I32MAX I32(1073741824)



#endif

